---
# tasks file for helm | EL Family

- name: EL Family | Downloading and extracting {{ helm_app }} {{ helm_version }}
  ansible.builtin.unarchive:
    src: "{{ helm_dl_url }}"
    dest: "{{ helm_bin_path }}"
    extra_opts:
      - --strip-components=1
      - "{{ helm_os }}-{{ helm_architecture_map[ansible_architecture] }}/{{ helm_app }}"
    remote_src: yes
    owner: "{{ helm_file_owner }}"
    group: "{{ helm_file_group }}"
    mode: "{{ helm_file_mode }}"
